'use strict';

// Prepares a deploy:
//  1. public/        the browser files (served as static assets)
//  2. worker/game-core.js   game.js wrapped in a function so the Worker can run the same rules
//     (Workers cannot eval or use node:vm, so the source is embedded at build time).

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');

const CLIENT_FILES = [
  'index.html', 'company.html', 'market.html', 'finance.html', 'bank.html', 'login.html',
  'style.css', 'game.js', 'net.js', 'shared.js', 'world-map.js', 'city.js', 'company.js',
  'market.js', 'finance.js', 'bank.js', 'login.js',
];

// Overwrite in place (not delete) so a running `wrangler dev` keeps working.
fs.mkdirSync(PUBLIC, { recursive: true });
for (const file of CLIENT_FILES) {
  const from = path.join(ROOT, file);
  if (!fs.existsSync(from)) throw new Error(`Missing client file: ${file}`);
  fs.copyFileSync(from, path.join(PUBLIC, file));
}

const source = fs.readFileSync(path.join(ROOT, 'game.js'), 'utf8');
const core = `// GENERATED by scripts/build.js from game.js. Do not edit.
export function createCore() {
${source}
;return {
  get state() { return state; },
  set state(value) { state = value; },
  get notices() { return notices; },
  clearNotices() { notices = []; },
  gameService, LocalGameService, newGame, hydrateGame, serializeGame, runWorldDay,
  settleRivalSale, isValidPlotId, plotPrice, creditReport, netWorth,
  MULTIPLAYER_WORLD_DAY_MS, START_CASH, WORLD_PLOT_COUNT,
};
}
`;
fs.mkdirSync(path.join(ROOT, 'worker'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'worker', 'game-core.js'), core, 'utf8');
console.log(`Built public/ (${CLIENT_FILES.length} files) and worker/game-core.js`);
